#ifndef _HEADEROBJ_H_
#define _HEADEROBJ_H_

#include "Singleton.h"
#include "Player.h"
#include "Brick.h"
#include "Candle.h"
#include "Ghouls.h"
#include "MedusaHeads.h"
#include"Bats.h"
#include "Panthers.h"
#include "Fishmen.h"
#include "Water.h"
#include "Fire.h"
#include "LargeCandle.h"
#include "Stair.h"
#include "AxeKnights.h"
#include "BoneTowers.h"
#include "MovingPlatform.h"
#include "Medusa.h"
#include "Door.h"
#include "TrapDoor.h"
#include "CastleGate.h"
#include "OpenDoor.h"
#include "MagicalBall.h"
#include "Ghosts.h"
#include "Barrier.h"
#include "BrickHide.h"
#include "Skeletons.h"
#include "Fleaman.h"
#endif